import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Layouts/Header";
import Sidebase from "@/Components/Layouts/Sidebase";
import I18Provider from "@/Contexts/I18Provider.jsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  const { lang } = params
  return (

    <html lang="en">

      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com"  />
        <link href="https://fonts.googleapis.com/css2?family=Cal+Sans&family=Gulzar&display=swap" rel="stylesheet" />
      </head>
      <body
        style={
          lang == 'ar'
            ? {
              fontFamily:'"Gulzar", serif',
              fontWeight: 400
            }
            : {}}
      className={` ${lang != 'ar' && geistSans.className} `}
      >
        {/* For the client side , i have  another function for the server side */}
        <I18Provider>
          {/* ------------ */}
          <Header />
          <div className="w-full  flex justify-start items-start h-[90vh] gap-3">
            <Sidebase />
            <main className="max-h-full w-full h-full overflow-auto">
              {children}
            </main>
          </div>
        </I18Provider>
      </body>
    </html>
  );
}
